# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: blue
  font_size: M

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Vahid Shariati | Bioinformatician | Genomics | Artificial Intelligence (AI)'
    twitter: 'https://twitter.com/vshariati'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
# Contact
appointment_url: 'https://calendar.app.google/ASaj6RGvcb4zcgim8'
# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Vahid Shariati"
      # Logo filename in `assets/media/` folder
      # filename: "logo.svg"
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© 2024 All rights are reserved.' #Me. This work is licensed under {license}
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: true
  highlight: true
  highlight_languages:
  - r
  - python
  - latex
  avatar:
  gravatar: false
  shape: circle
  publications:
    date_format: January 2006
    citation_style: apa
  projects:
    post_view: 2
    publication_view: 2
    talk_view: 2
  breadcrumb:
    page_types:
      book: true
  show_related:
  book: true
  page: true
  post: true
  project: true
  publication: true
  event: true
  reading_time: true
  section_pager: true
  docs_section_pager: true

